repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [sqlfluff-templater-jinja]
      - id: sqlfluff-fix
        additional_dependencies: [sqlfluff-templater-jinja]
